language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo apt-get install python
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo pip install -U pip
  - sudo python ez_setup.py
  - sudo pip install --upgrade Pweave
  - sudo apt-get install python-matplotlib
  - sudo apt-get install nano
  - sudo apt-get install vim
  
before_script:
  - git config --global user.email "arturoinosencio@gmail.com"
  - git config --global user.name "Wowip"
  
# command to run tests
script: 
  - Pweave -f pandoc ejemplo2.Pnw
  - Pweave -f pandoc ejemplo3.Pnw
  
after_script:
  - git clone git@github.com:Wowip/scrum_developer.git
  - ls -a
  - vim id_rsa
  - git add .
  - git pull
  - git commit -m "a√±adiendo pruebas"
  - git push origin master






