language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo apt-get install python
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo pip install -U pip
  - sudo python ez_setup.py
  - sudo pip install --upgrade Pweave
  - sudo apt-get install python-matplotlib
  
before_script:
  - git config --global user.email "arturoinosencio@gmail.com"
  - git config --global user.name "Wowip"
  
# command to run tests
script: 
  - Pweave -f pandoc ejemplo2.Pnw
  - Pweave -f pandoc ejemplo3.Pnw
  - ./build.sh
#Colocando que solo se corra por def
branches:
  only:
  - def

#Poniendo el token de manera segura  
env:
  global:
    secure: a04bbc16b409cf2a7a5f98be5b4fe6d5a42a0a46

#Después de que lo convierta
after_success:
  - git config remote.origin.url https://Wowip:a04bbc16b409cf2a7a5f98be5b4fe6d5a42a0a46@github.com/Wowip/scrum_developer.git
  - ls -a
  - git add .
  - git pull
  - git commit -m "Añadiendo archivos faltantes.md"
  - git config --global credential.helper
  - git push -fq origin master


