language: python
python:
  - "2.7"

  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo apt-get install python
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo pip install -U pip
  - sudo python ez_setup.py
  - sudo pip install --upgrade Pweave
  - sudo apt-get install python-matplotlib
  - sudo apt-get install nano
  - sudo apt-get install vim
  - sudo apt-get install gcc
  - sudo apt-get install gfortran
  - sudo wget https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
  - tar -xvzf R-latest.tar.gz
  - cd R-patched
  - sudo ./configure
  - make
  - cd ..
  - wget https://cran.r-project.org/src/contrib/knitr_1.11.tar.gz
  - sudo R CMD INSTALL knitr_1.11.tar.gz


  
# command to run tests
script: 
  - sh scrip_prueba.sh
  - Rscript -e "R.version"
  - Rscript -e "library(knitr); knit('ejemplo.Rmd')"

  
  
after_script:
  - ls
  - cd manuscript
  - ls
  - ls -l *.md | sort -g | awk '{print $9}'
  - ls *.md | sort -g > Book.txt
  - cd ..
  - ls
  - git init
  - git remote -v 
  - git remote remove origin
  - git remote add origin git@github.com:Wowip/scrum_developer.git  
  - sudo chmod 600 .ssh/id_rsa
  - sudo chmod 600 .ssh/id_rsa.pub
  - ls -a
  - ls -al .ssh
  - eval "$(ssh-agent -s)"
  - ssh-add .ssh/id_rsa
  - ssh -T git@github.com
  - git checkout master
  - git add .
  - git commit -m "a√±adiendo pruebas"
  - git push origin master






