language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo apt-get install python
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo pip install -U pip
  - sudo python ez_setup.py
  - sudo pip install --upgrade Pweave
  - sudo apt-get install python-matplotlib
  
before_script:
  
# command to run tests
script: 
  - Pweave -f pandoc ejemplo2.Pnw
  - Pweave -f pandoc ejemplo3.Pnw

#Después de que lo convierta
after_success:
  - git config --global user.email "arturoinosencio@gmail.com"
  - git config --global user.name "Wowip"
  - curl -u Wowip:608a9278e643e592de3c2558270ffd8c885b570d https://api.github.com/Wowip
  - git clone https://Wowip:608a9278e643e592de3c2558270ffd8c885b570d@github.com/Wowip/scrum_developer.git --branch=master master
  - git remote rm origin
  - git remote add origin https://Wowip:608a9278e643e592de3c2558270ffd8c885b570d@github.com/Wowip/scrum_developer.git
  - ls
  - git add -f .
  - git pull remote master
  - git commit -m "Añadiendo archivos faltantes.md"
  - git push -fq origin master


